# Generated by Django 3.0.5 on 2020-04-26 17:02

from django.db import migrations


CATEGORY_GROUPS = sorted([
    ('Credits', 'expense'),
], key=lambda elem: (elem[1], elem[0]))

CATEGORIES = sorted([
    ('Fuel', 'Transport'),
    ('Other', 'Other Expenses'),
    ('Online Services', 'Services'),
    ('Flat', 'Credits')
], key=lambda elem: (elem[1], elem[0]))

def add_category_groups(apps, schema_editor):
    CategoryGroup = apps.get_model('backend', 'CategoryGroup')
    for elem in CATEGORY_GROUPS:
        print(elem)
        CategoryGroup.objects.get_or_create(name=elem[0], type=elem[1])


def add_categories(apps, schema_editor):
    Category = apps.get_model('backend', 'Category')
    CategoryGroup = apps.get_model('backend', 'CategoryGroup')
    for elem in CATEGORIES:
        print(elem)
        group = CategoryGroup.objects.get(name=elem[1])
        print(group.name)
        Category.objects.get_or_create(name=elem[0], group=group)
        print("ok")


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200505_2239'),
    ]

    operations = [
        migrations.RunPython(add_category_groups),
        migrations.RunPython(add_categories),
    ]
