# Generated by Django 3.0.5 on 2020-05-30 17:51

from django.db import migrations


ACCOUNTTYPES = ['RETIREMENT', 'NORMAL', 'INVESTMENT', 'CREDIT']


def add_currencies(apps, schema_editor):
    AccountType = apps.get_model('backend', 'AccountType')
    for elem in ACCOUNTTYPES:
        print(elem)
        AccountType.objects.get_or_create(type=elem)


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200530_1749'),
    ]

    operations = [
        migrations.RunPython(add_currencies),
    ]
