# Generated by Django 3.0.5 on 2020-05-30 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200530_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='backend.AccountType'),
            preserve_default=False,
        ),
    ]
