# Generated by Django 3.0.5 on 2020-05-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_auto_20200530_1835"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset", name="cost", field=models.FloatField(null=True),
        ),
    ]
