# Generated by Django 3.0.5 on 2020-05-05 23:07

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorizationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rule', django.contrib.postgres.fields.jsonb.JSONField()),
                ('effect_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='categorizationrule',
            constraint=models.UniqueConstraint(fields=('user_id', 'name'), name='unique_rule_name_per_user'),
        ),
    ]
